// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwgfgs2kI0XJt9dm7mRPI95hovAJf4kM',
    appId: '1:635490492887:web:812fbc22067c724db9eb92',
    messagingSenderId: '635490492887',
    projectId: 'flutterassignment-671fe',
    authDomain: 'flutterassignment-671fe.firebaseapp.com',
    storageBucket: 'flutterassignment-671fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSMrfxMMXkeJrjtgBwN599N--dB6nCOo',
    appId: '1:635490492887:android:2b85813ae47d77f1b9eb92',
    messagingSenderId: '635490492887',
    projectId: 'flutterassignment-671fe',
    storageBucket: 'flutterassignment-671fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX1GaKNS_Zn8sbwUdGMTyyDg_sPyMR3fg',
    appId: '1:635490492887:ios:d7112997870f5cd3b9eb92',
    messagingSenderId: '635490492887',
    projectId: 'flutterassignment-671fe',
    storageBucket: 'flutterassignment-671fe.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX1GaKNS_Zn8sbwUdGMTyyDg_sPyMR3fg',
    appId: '1:635490492887:ios:d7112997870f5cd3b9eb92',
    messagingSenderId: '635490492887',
    projectId: 'flutterassignment-671fe',
    storageBucket: 'flutterassignment-671fe.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkwgfgs2kI0XJt9dm7mRPI95hovAJf4kM',
    appId: '1:635490492887:web:812fbc22067c724db9eb92',
    messagingSenderId: '635490492887',
    projectId: 'flutterassignment-671fe',
    authDomain: 'flutterassignment-671fe.firebaseapp.com',
    storageBucket: 'flutterassignment-671fe.firebasestorage.app',
  );

}